FIND_PATH(PPTHREAD_INCLUDE_DIR thread.h /usr/include/ppthread /usr/local/include/ppthread)

FIND_LIBRARY(PPTHREAD_LIBRARY NAMES ppthread PATH /usr/lib /usr/local/lib) 

IF (PPTHREAD_INCLUDE_DIR AND PPTHREAD_LIBRARY)
   SET(PPTHREAD_FOUND TRUE)
ENDIF (PPTHREAD_INCLUDE_DIR AND PPTHREAD_LIBRARY)


IF (PPTHREAD_FOUND)
   IF (NOT PPTHREAD_FIND_QUIETLY)
      MESSAGE(STATUS "Found PPTHREAD: ${PPTHREAD_LIBRARY}")
   ENDIF (NOT PPTHREAD_FIND_QUIETLY)
ELSE (PPTHREAD_FOUND)
   IF (PPTHREAD_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find PPTHREAD")
   ENDIF (PPTHREAD_FIND_REQUIRED)
ENDIF (PPTHREAD_FOUND)